<MyScreenManager>:
    LoginScreen:
        md_bg_color: self.theme_cls.backgroundColor
        name: 'login'
    HomeScreen:
        md_bg_color: self.theme_cls.backgroundColor
        name: 'home'
    RegisterationScreen:
        md_bg_color: self.theme_cls.backgroundColor
        name: 'register'
    AuthenticationScreen: 
        md_bg_color: self.theme_cls.backgroundColor
        name: "authenticate"